Create dropdown
Olga-Skoroded/toxin-group-project pull request #10
Opened 2020-09-07 14:57 UTC by Fr0stmourne

2020-09-08 05:10 UTC, krashaen requested changes

2020-09-08 05:10 UTC, krashaen commented on components/Dropdown/Dropdown.tsx
> +    wordForms: WordForms;
я б вынес в отдельный интерфейс группу, она возможно где то еще понадобится)

2020-09-08 05:10 UTC, krashaen commented on components/Dropdown/Dropdown.tsx
> +    initialValue?: number;
итем бы тоже отдельный интерфейс сделал)

2020-09-08 05:10 UTC, krashaen commented on components/Dropdown/Dropdown.tsx
> +    applyChanges();
а зачем применять значения фильтров, если я не нажал применить? Когда я кликнул вне дропдауна я хочу его закрыть, а не применить фильтр)

2020-09-08 05:11 UTC, krashaen commented
+ не забывай `npm run lint` запускать :)
![image](https://user-images.githubusercontent.com/12808495/92435347-53d03d80-f1cc-11ea-8a20-31feb7e42ca9.png)

2020-09-09 02:03 UTC, krashaen commented on components/Dropdown/Dropdown.tsx
> +    applyChanges();
так а тут ответа не будет?)

2020-09-09 02:04 UTC, krashaen commented on components/Dropdown/Dropdown.tsx
> +    let groupResults;
лучше объявить констом переменную ниже, так она не защищена от мутации

2020-09-09 02:08 UTC, krashaen commented on components/Dropdown/Dropdown.tsx
> +          .reduce((acc, el) => acc + el.currentValue, 0);
а тут нельзя просто длину взять после фильтра?) зачем прям редьюс юзать для суммы элементов?)

2020-09-09 02:17 UTC, krashaen commented on components/Dropdown/Dropdown.tsx
> +            <S.ResetButton type="button" modifiers={dropdownState.every((item) => !item.currentValue) && 'hidden'} onClick={handleResetClick}>
все вычисления modifiers я бы вынес в отдельную декларативную переменную

2020-09-09 07:21 UTC, Fr0stmourne commented on components/Dropdown/Dropdown.tsx
> +    applyChanges();
так я же этот момент исправил) теперь функция handleApplyClick триггерится только по кнопке применить, а если кликнуть вне дропдауна, то он просто закроется

2020-09-09 07:26 UTC, Fr0stmourne commented on components/Dropdown/Dropdown.tsx
> +          .reduce((acc, el) => acc + el.currentValue, 0);
не очень понял, как тут обойтись длиной массива, если там массив объектов типа 
``` { group: 'guests', currentValue: 2, ... } ``` 
мне же надо не количество этих объектов, а именно значение ключа вытащить из каждого)

2020-09-09 07:44 UTC, Fr0stmourne commented on components/Dropdown/Dropdown.tsx
> +    let groupResults;
я ее определяю внутри if с проверкой, что группировка вообще есть, а потом мне эту переменную надо использовать вне этого блока, поэтому вынес на уровень выше определение. Мне кажется, так читается лучше, чем если определить через const,  убрать if и потом при каждом обращении проверять что переменная есть

2020-09-09 07:53 UTC, Fr0stmourne commented on components/Dropdown/Dropdown.tsx
> +            <S.ResetButton type="button" modifiers={dropdownState.every((item) => !item.currentValue) && 'hidden'} onClick={handleResetClick}>
решил вынести только вычисление булевого значения наружу, саму строчку модификатора оставил в jsx, как в такой же ситуации чуть выше, так удобнее показалось
```
modifiers={isResetHidden && 'hidden'}
```

2020-09-10 11:40 UTC, Fr0stmourne commented on components/Dropdown/Dropdown.tsx
> +            <S.ResetButton type="button" modifiers={dropdownState.every((item) => !item.currentValue) && 'hidden'} onClick={handleResetClick}>
Решил отказаться от этой библиотеки, сделал средствами styled-components, так что уже неактуально

2020-09-11 05:38 UTC, krashaen commented on components/Dropdown/Dropdown.tsx
> +          .reduce((acc, el) => acc + el.currentValue, 0);
а, ок, чет я тупанул)

2020-09-11 06:12 UTC, dashkevi4mike requested changes
как то тяжело воспринимается код компоненты) кажется что ее можно было сделать попроще. посмотри вот такую реализацию) все довольно легко читается

2020-09-11 11:37 UTC, SigidinIlya commented on components/Dropdown/Dropdown.tsx
> +  label?: string;
Все необязательные значения в типе должны быть снизу)

2020-09-11 12:08 UTC, Olga-Skoroded reviewed
Эти заголовки темнее должны быть вроде
![itemtitle](https://user-images.githubusercontent.com/68814270/92923611-f0f7d400-f461-11ea-8cb4-ca8ba73f057e.png)

2020-09-14 18:23 UTC, AkhmadBabaev commented
Для disabled кнопок можно убрать cursor: pointer.

2020-09-14 18:29 UTC, AkhmadBabaev approved these changes

2020-09-14 22:01 UTC, Ilanevazno approved these changes

2020-09-14 22:05 UTC, SigidinIlya approved these changes

2020-09-15 02:22 UTC, Olga-Skoroded approved these changes

2020-09-15 05:01 UTC, krashaen approved these changes

2020-09-15 09:40 UTC, merged