10 create like button
Olga-Skoroded/toxin-group-project pull request #19
Opened 2020-09-10 10:25 UTC by SigidinIlya

2020-09-10 15:32 UTC, AkhmadBabaev commented on components/LikeButton/LikeButton.styles.ts
> +        right: -1px;
Нужно заменить px на rem )

2020-09-10 15:32 UTC, AkhmadBabaev commented on components/LikeButton/LikeButton.styles.ts
> +  ${
**Div** по имени LikaSpan😁, ну и **label** не должен содержать в себе **div**.

2020-09-11 06:02 UTC, krashaen approved these changes

2020-09-11 11:27 UTC, Fr0stmourne requested changes

2020-09-11 11:27 UTC, Fr0stmourne commented on components/LikeButton/LikeButtonContainer.tsx
> +  const [likesCount, setLikesCount] = useState(0);
нужно добавить пропс с начальным количеством лайков, это же не всегда 0)

2020-09-11 11:27 UTC, Fr0stmourne commented on components/LikeButton/LikeButton.styles.ts
> +      width: 2.7rem;
из-за фиксированной ширины проблемы с переполнением
![image](https://user-images.githubusercontent.com/46089168/92918690-546d0c00-f438-11ea-9d75-792ce87ea550.png)

2020-09-11 11:27 UTC, Fr0stmourne commented on components/LikeButton/LikeButtonContainer.tsx
> +};
А зачем выделять отдельную сущность LikeButtonContainer? мне кажется, определить обработчики и прокидывать пропсы можно прям в LikeButton, и этот же компонент экспортировать

2020-09-11 11:27 UTC, Fr0stmourne commented on pages/guide/elements/index.tsx
> +            <S.Container>
Тут слетел отступ

2020-09-11 11:27 UTC, Fr0stmourne commented on components/LikeButton/LikeButton.styles.ts
> +        fill: ${isActive ? colors.primary : '#fff'};
цвет неактивной кнопки лучше наверное из темы тоже достать, там это defaultBackground вроде

2020-09-11 11:27 UTC, Fr0stmourne commented on pages/guide/elements/elements.styles.ts
> +export const LikeButtonWrapper = styled.div`
как я понял, мы все же решили придерживаться экспорта всех сущностей в конце файла, да и по стандартам так)

2020-09-11 11:27 UTC, Fr0stmourne commented on components/LikeButton/LikeButton.styles.ts
> +      background: #fff;
тут тоже из темы лучше взять

2020-09-11 11:27 UTC, Fr0stmourne commented on components/LikeButton/LikeButtonContainer.tsx
> +  const [isLikeButtonPressed, setLikeButtonStatus] = useState(false);
я бы так и оставил isLikeActive, setIsLikeActive, раз в остальных местах такое именование

2020-09-11 11:54 UTC, Olga-Skoroded reviewed
Сейчас на импорты ругается, поправь, если еще не поправил) 
![import](https://user-images.githubusercontent.com/68814270/92922505-21d70980-f460-11ea-8a73-38f2603b439c.png)
![import 2](https://user-images.githubusercontent.com/68814270/92922508-23083680-f460-11ea-8d8a-f25d27d02e14.png)

2020-09-11 12:12 UTC, Olga-Skoroded approved these changes

2020-09-11 14:32 UTC, SigidinIlya commented on components/LikeButton/LikeButtonContainer.tsx
> +};
Обговаривали этот момент сегодня. Т.е мне нужно будет изучить React final form и взвесить что из этого лучше использовать, поэтому пока приняли решение оставить текущую реализацию, в будущем при принятии точного решения по стейт менджменту нужно будет соответственно отрефакторить.

2020-09-14 17:28 UTC, AkhmadBabaev approved these changes

2020-09-14 19:07 UTC, Fr0stmourne approved these changes

2020-09-15 10:34 UTC, merged