create auth page, redux, saga
Olga-Skoroded/toxin-group-project pull request #211
Opened 2020-10-08 01:19 UTC by SigidinIlya

2020-10-08 06:54 UTC, viktoriya-ch commented on components/AccountEntry/AccountEntry.tsx
> +const AccountEntry: React.FC<Props> = (props: Props): JSX.Element => {
А LoginForm не будет более понятным названием?

2020-10-08 06:54 UTC, viktoriya-ch commented on components/AccountEntry/AccountEntry.tsx
> +type userData = {
Почему с маленькой буквы?)

2020-10-08 06:54 UTC, viktoriya-ch commented on components/AuthPage/components/MainContent.tsx
> +const InnerPage: React.FC<Props> = (props: Props): JSX.Element => {
Файл называется `MainContent`, а компонент `InnerPage`

2020-10-08 06:54 UTC, MorganaLF commented on components/AuthPage/components/MainContentContainer.tsx
> +export default connect(mapState, mapDispatch)(InnerPage);
А зачем это в отдельный файл выносить? Почему не в `MainContent` сразу в `connect` завернуть?

2020-10-08 06:54 UTC, MorganaLF commented on components/CardsPage/CardsPage.tsx
> +const mockFunction = () => {
В таких местах лучше ставить TODO, чтобы оно случайно так и не осталось висеть) И лучше делать асинхронные моки, раз у тебя тут асинхронный запрос предполагается.

2020-10-08 06:54 UTC, MorganaLF commented on components/Header/HeaderUserProfile/HeaderUserProfile.tsx
> +    <S.Link href="">{displayName}</S.Link>
А куда ссылка делась?

2020-10-08 06:54 UTC, MorganaLF commented on pages/auth/index.tsx
> +const auth: React.FC = (): JSX.Element => <AuthPage />;
Имя реакт-компонентов всегда с большой буквы должно быть

2020-10-08 06:54 UTC, MorganaLF commented on redux/reducers.ts
> +  isAuthSuccess?: boolean;
А почему все опциональное?

2020-10-08 06:54 UTC, MorganaLF commented on redux/reducers.ts
> +  authStatusText?: string | unknown;
А откуда тут тип unknown? Должна быть всегда строка, раз у тебя initial пустая строка. Или лучше вообще initial поставить null, чтобы явно по типу видеть, что текст не задан.

2020-10-08 06:54 UTC, MorganaLF commented on redux/reducers.ts
> +  displayName: false,
А что такое displayName? Не будет путаницы в названиях с реактовским displayName? И что у него за странный тип: строка либо булево значение? Тогда уж string либо null.

2020-10-08 06:54 UTC, MorganaLF commented on redux/sagas.tsx
> +    const authStatus: UserCredential | unknown = yield call(Api.auth.signIn, email, password);
Чет по типам совсем ничего не работает. Пробовал тут вывести нормальный тип, чтобы без юниона было? Посмотри в сети всякие решения, как вывести тип из call()

2020-10-08 06:54 UTC, MorganaLF commented on redux/constant.ts
> +const AUTH_PROCESS = 'AUTH_PROCESS';
Файл наверное надо constants назвать, а не constant.

2020-10-08 07:39 UTC, SigidinIlya commented on components/AccountEntry/AccountEntry.tsx
> +const AccountEntry: React.FC<Props> = (props: Props): JSX.Element => {
Мне кажется что одинаково

2020-10-08 07:40 UTC, SigidinIlya commented on components/AuthPage/components/MainContentContainer.tsx
> +export default connect(mapState, mapDispatch)(InnerPage);
ну, как-то исторически сложилось, что люди в отдельном файле хранят, насколько я знаю

2020-10-08 07:41 UTC, SigidinIlya commented on components/CardsPage/CardsPage.tsx
> +const mockFunction = () => {
TODO на что?)
Мне просто нужно было любую функцию передать, т.к компонент ожидает колбэк)

2020-10-08 21:38 UTC, SigidinIlya commented on redux/reducers.ts
> +  displayName: false,
поправил на null. По поводу displayName решил далеко не ходить, и использовать это имя прям как использовано у нас в API.

2020-10-09 05:50 UTC, MorganaLF commented on components/CardsPage/CardsPage.tsx
> +const mockFunction = () => {
> TODO на что?)
Чтобы не забыть, что у тебя где-то мок висит)
У тебя же в последствии должен быть настоящий запрос там? Или что это?)

2020-10-09 06:05 UTC, MorganaLF commented on components/AccountEntry/AccountEntry.tsx
> +const AccountEntry: React.FC<Props> = (props: Props): JSX.Element => {
ок

2020-10-09 06:13 UTC, SigidinIlya commented on components/CardsPage/CardsPage.tsx
> +const mockFunction = () => {
Нет, это тестовая страница, запросов там не должно быть )

2020-10-09 14:45 UTC, Azmodan95 approved these changes

2020-10-09 17:38 UTC, MorganaLF commented on components/CardsPage/CardsPage.tsx
> +const mockFunction = () => {
> Нет, это тестовая страница, запросов там не должно быть )

Тогда не вижу смысла ее отдельно наверх выносить, сразу передать что-то вроде `requestToAuth={() => console.log('Successfull auth')}`.
Загадочная функция, стоящая отдельно и возвращающая 5 + 5 может сбивать с толку)

2020-10-13 14:13 UTC, MorganaLF approved these changes

2020-10-14 04:35 UTC, Olga-Skoroded approved these changes

2020-10-14 07:04 UTC, Azmodan95 commented on components/AccountEntry/AccountEntry.styled.ts
> +const GoogleIcon = styled(GTranslateIcon)`
Может стоит другую иконку выбрать? Просто эта иконка с гугл переводчика в данном случае как мне кажется не совсем подходит 
![image](https://user-images.githubusercontent.com/51163508/95954748-7295a580-0e04-11eb-8510-6292f52e1b2e.png)

2020-10-14 07:32 UTC, Fr0stmourne commented on components/MainLayout/MainLayout.tsx
> +});
если там всё один в один переносится, может просто сам state и возвращать?

2020-10-14 08:18 UTC, Azmodan95 approved these changes

2020-10-14 08:18 UTC, Fr0stmourne approved these changes

2020-10-14 14:10 UTC, krashaen requested changes

2020-10-14 14:10 UTC, krashaen commented on components/AuthPage/AuthPage.tsx
> +    <>
без фрагметна будет тоже самое)

2020-10-14 14:10 UTC, krashaen commented on redux/reducers.ts
> +export type State = {
типизация стейта должна лежать с частью логики, то есть все что касается с auth должно быть затипизировано отдельно

2020-10-14 14:10 UTC, krashaen commented on redux/reducers.ts
> +    case BREAK_AUTH_PROCESS:
это все должно лежать явно не в рутовом редюсере, я так понимаю ты хочешь все редюсеры всего проекта тут писать?

2020-10-14 14:10 UTC, krashaen commented on redux/sagas.tsx
> +      });
зачем тут переносы делать?) или это ваш форматер так делает? выглядит не очень

2020-10-14 14:10 UTC, krashaen commented on redux/sagas.tsx
> +    > {
очень странное форматирование

2020-10-14 14:10 UTC, krashaen commented on redux/sagas.tsx
> +const authStateChangedCallback = (): Promise<User> => {
не понятно зачем это промис вообще нужен) ниже в вызове описал мысли

2020-10-14 14:10 UTC, krashaen commented on redux/sagas.tsx
> +    const result: User = yield call(authStateChangedCallback);
почему бы тут сразу не заелдить Api.auth.onStateChanged?
если через промис ты хотел ошибкуобработать, то она у тебя по идеи должна упасть в кетч тут)

2020-10-14 14:10 UTC, krashaen commented on components/AuthPage/AuthPage.tsx
> +const mapState = (state) => state;
очень не хорошо) что ты весь стейт засунул в компоненту)
и получается при любом изменении во всем редакс стэйте, этот компонент будет ререндерится
так как он родительский то скорее всего все приложение будет перерисовываться на каждый чих редакса) но это не точно

2020-10-14 14:10 UTC, krashaen commented on redux/reducers.ts
> +export type State = {
вообще нужно все по фичам делить, тоесть у каждой фукнциональности должна быть свои файлы redusers, actions, sagas

2020-10-14 14:13 UTC, SigidinIlya commented on redux/sagas.tsx
> +    > {
Это форматтер

2020-10-14 14:13 UTC, SigidinIlya commented on redux/sagas.tsx
> +      });
Это форматтер

2020-10-15 12:55 UTC, SigidinIlya commented on redux/sagas.tsx
> +    const result: User = yield call(authStateChangedCallback);
Сразу заелдить Api.auth.onStateChanged не получится, т.к это стандартная функция АПИ файрбейса, которая вызывается при каждом изменении активности пользователя, функция принимает в себя колбэк который в аргументах имеет либо объект с данными авторизацией, либо null. Поэтому если мы заелдим её, то не сможем никак узнать о активности пользователя.

2020-10-16 04:31 UTC, krashaen approved these changes

2020-10-16 07:25 UTC, merged