remove action type constants
Olga-Skoroded/toxin-group-project pull request #293
Opened 2020-11-10 11:59 UTC by Azmodan95

2020-11-11 13:13 UTC, SigidinIlya approved these changes

2020-11-12 08:17 UTC, Fr0stmourne commented on components/PersonalInfoPage/components/EditPersonalInfo/components/EditBirthday/EditBirthday.tsx
> +  completionUpdateAdditionalUserData,
что-то тут странное с названиями, функции с существительными, может будет лучше `completeAdditionalUserDataUpdate` или типа того?

2020-11-12 08:17 UTC, Fr0stmourne commented on redux/Auth/redux/actions.ts
> -};
а чего ты решил сменить этот экспорт на экспорт каждой переменной отдельно?

2020-11-12 09:07 UTC, Azmodan95 commented on redux/Auth/redux/actions.ts
> -};
Чтобы было хоть какое-то однообразие по проекту, в одном файле экспорты в низу были, в другом возле каждой переменной. В частности где я создавал что-то экспорты были в самом низу, но по большей части проекта экспорты были возле каждой переменной (не учитывая дефолтные экспорты), поэтому и решил сделать возле каждой переменной, тем более так меньше кода получается.

2020-11-12 11:58 UTC, Fr0stmourne commented on redux/Auth/redux/actions.ts
> -};
вообще мне казалось, что у нас по большей части внизу файла были экспорты, странно)

2020-11-12 12:07 UTC, Fr0stmourne commented on components/PersonalInfoPage/components/EditPersonalInfo/components/EditBirthday/EditBirthday.tsx
> +  stopUpdateAdditionalUserData: completeUpdateAdditionalUserData,
`completeUpdateAdditionalUserData` лучше на `completeAdditionalUserDataUpdate`, у тебя даже чуть раньше в `completePasswordUpdate` update в конце

2020-11-12 12:13 UTC, Azmodan95 commented on redux/Auth/redux/actions.ts
> -};
Тут не буду спорить, возможно я ошибался, и тут возможно все не так однозначно. Я не правил по всему проекту, я поправил только в сагах. Ты предлагаешь перенести все вниз?)

2020-11-13 03:55 UTC, Olga-Skoroded approved these changes

2020-11-13 06:14 UTC, Fr0stmourne commented on redux/Auth/redux/actions.ts
> -};
лучше было бы перенести просто потому, что в какой-то момент придется при рефакторинге приводить к одному виду везде, а сейчас там вроде бОльшая часть с экспортами в конце файла (но это не точно). Я бы тебе посоветовал посмотреть, каких экспортов больше по проекту и в таком же стиле и сделать)

2020-11-13 06:14 UTC, Fr0stmourne approved these changes

2020-11-13 12:43 UTC, Azmodan95 commented on redux/Auth/redux/actions.ts
> -};
Да действительно, посмотрел через поиск, экспорт внизу используется в большем количестве файлов. Переделал.

2020-11-16 09:10 UTC, hersveit requested changes

2020-11-16 09:10 UTC, hersveit commented on redux/Profile/redux/sagas/index.ts
>      });
Надо использовать готовый метод экшена, который выдаст соответствующий объект. Тут и везде
То же само я писал в этом ПР https://github.com/Olga-Skoroded/toxin-group-project/pull/297 . Скооперируйтесь как-нибудь)

2020-11-16 14:19 UTC, Azmodan95 commented on redux/Profile/redux/sagas/index.ts
>      });
Ну типы экшенов я до этого подправил) А вот экшены которые возвращают нужный объект добавил.

2020-11-18 07:35 UTC, hersveit approved these changes

2020-11-18 07:43 UTC, merged