rewrite react fc to memo
Olga-Skoroded/toxin-group-project pull request #294
Opened 2020-11-11 11:32 UTC by Azmodan95

2020-11-12 08:06 UTC, SigidinIlya approved these changes

2020-11-12 08:34 UTC, Fr0stmourne commented on components/AccountEntry/AccountEntry.tsx
> +AccountEntry.displayName = 'AccountEntry';
а из-за мемоизации пропадает где-то в девтулзах название компонента или зачем эта штука нужна?

2020-11-12 08:55 UTC, Azmodan95 commented on components/AccountEntry/AccountEntry.tsx
> +AccountEntry.displayName = 'AccountEntry';
Не уверен что действительно пропадает, но по причине того что мы передаем memo анонимную функцию eslint ругается на то что у функции нет имени, и просит задать displayName. Другой вариант можно было при дефолтном экспорте memo применить, но так как у нас будут убираться дефолтные экспорты этот вариант уже не подходить.

2020-11-12 11:51 UTC, Fr0stmourne approved these changes

2020-11-13 03:54 UTC, Olga-Skoroded approved these changes

2020-11-13 09:39 UTC, hersveit requested changes

2020-11-13 09:39 UTC, hersveit commented on components/AccountEntry/AccountEntry.tsx
> +AccountEntry.displayName = 'AccountEntry';
Зачем везде `displayName` стоит? Возникает необходимость дебага?

2020-11-13 09:39 UTC, hersveit commented on components/ArrowButton/ArrowButton.tsx
> +const ArrowButton = memo(({ ...rest }: Props) => (
Бессмысленно дестрактить 
```
memo((props: Props) => ...);
```

2020-11-13 09:39 UTC, hersveit commented on components/Benefits/Benefits.tsx
> +const Benefits: ComponentType<WithTranslation & Props> = memo(({ items, t }: Props) => (
Здесь и везде очень странно реализовано слияние с интерфейсом переводов. Само определение `ComponentType` не нужно и пропсы можно определить сильно проще 
```
type Props = WithTranslation & {
  items: Array<
    {
      term: string;
      definition: string;
      icon: string;
    } & S.Icon
  >;
};

const Benefits = memo(({ items, t }: Props) => ...);
```

Вопрос в том, где это менять? Тут или в другом ПР.  Работа тут чисто рутинная, но нужно просто понять разницу и как работает объединение интерфейсов и как работают генерики.

2020-11-13 09:54 UTC, Azmodan95 commented on components/AccountEntry/AccountEntry.tsx
> +AccountEntry.displayName = 'AccountEntry';
Из-за того что мы memo передаем анонимную функцию, eslint ругается и просит задать displayName.
![image](https://user-images.githubusercontent.com/51163508/99058967-f29f5e80-25ae-11eb-96f9-f545e634abd9.png)

2020-11-13 11:28 UTC, hersveit commented on components/AccountEntry/AccountEntry.tsx
> +AccountEntry.displayName = 'AccountEntry';
Я думаю можно тогда просто вырубить это правило и убрать все `displayName`. Смысл есть только при дебаге, а когда он понадобится можно точечно добавлять на интересующие компоненты.

2020-11-13 11:56 UTC, Azmodan95 commented on components/Benefits/Benefits.tsx
> +const Benefits: ComponentType<WithTranslation & Props> = memo(({ items, t }: Props) => (
Исправил.

2020-11-13 11:57 UTC, Azmodan95 commented on components/AccountEntry/AccountEntry.tsx
> +AccountEntry.displayName = 'AccountEntry';
Убрал везде displayName.

2020-11-13 11:57 UTC, Azmodan95 commented on components/ArrowButton/ArrowButton.tsx
> +const ArrowButton = memo(({ ...rest }: Props) => (
Исправил.

2020-11-13 12:24 UTC, hersveit approved these changes

2020-11-16 06:40 UTC, merged