fixed global api
Olga-Skoroded/toxin-group-project pull request #297
Opened 2020-11-11 21:46 UTC by SigidinIlya

2020-11-12 08:37 UTC, Fr0stmourne approved these changes

2020-11-12 11:01 UTC, Azmodan95 approved these changes

2020-11-13 03:55 UTC, Olga-Skoroded approved these changes

2020-11-13 08:53 UTC, hersveit requested changes

2020-11-13 08:53 UTC, hersveit commented on redux/Auth/redux/sagas/index.tsx
> +  },
Это Action `RequestToAuth`. нужно указать готовый тип 
```typescript
data: RequestToAuth
```

2020-11-13 08:53 UTC, hersveit commented on redux/Registration/redux/sagas/index.ts
> +  },
то же что и выше
```
data: RegistrationRequest
```

2020-11-13 08:53 UTC, hersveit commented on redux/Profile/redux/sagas/index.ts
> +function* usernameUpdate({ api }: Dependencies, { payload }: UsernameUpdateRequest) {
`api` не используется. Депенденси сюда передавать в целом смысла не имеет.

2020-11-16 10:44 UTC, hersveit approved these changes

2020-11-17 08:58 UTC, merged