remove default exports
Olga-Skoroded/toxin-group-project pull request #310
Opened 2020-11-13 05:05 UTC by Olga-Skoroded

2020-11-13 07:00 UTC, Azmodan95 approved these changes

2020-11-13 10:23 UTC, hersveit requested changes

2020-11-13 10:23 UTC, hersveit commented on redux/Booking/types.ts
> +import { Props as RoomProps } from 'shared/view/components/Room/Room.types';
Чтобы не делать такие "эзы", лучше сразу пропсы именовать как `ComponentNameProps`. Импортировать такие пропсы будет удобнее, и IDE будет их подсказывать

2020-11-16 08:05 UTC, Fr0stmourne approved these changes

2020-11-16 08:10 UTC, SigidinIlya approved these changes

2020-11-18 07:36 UTC, hersveit approved these changes

2020-11-19 04:40 UTC, merged