#6 create input component
Olga-Skoroded/toxin-group-project pull request #4
Opened 2020-08-06 09:03 UTC by Olga-Skoroded

2020-08-06 10:50 UTC, krashaen commented on components/Input/Input.tsx
> +import styles from './Input.module.scss';
А зачем у стилей сначала `.module`?)

2020-08-06 10:50 UTC, krashaen commented on components/Input/Input.tsx
> +    onChange={(e) => onChange(e)}
OnChange должен сверху прилетать пропсом)

2020-08-06 10:50 UTC, krashaen commented on components/Input/Input.tsx
> +    {...rest}
Посмотри примеры rest пропсов, насколько я помню они должны быть первыми, при такой реализации есть риск, что перетрешь пропсы что идут выше

2020-08-06 10:50 UTC, krashaen commented on components/Input/Input.tsx
> +    className={styles.input}
а почему так?  класснеймы? мы обычно bem cn используем для именования)

2020-08-06 10:50 UTC, krashaen commented on pages/_app.tsx
> +  return <Component {...pageProps} />;
а что за `pageProps`?)

2020-08-06 10:50 UTC, krashaen commented on pages/guide/elements/index.tsx
> +  validateField(fieldName, value) {
валидацию и другие штуки, которые могут потребоваться где то еще, я бы предложил тебе класть в `shared/helpers`

2020-08-06 10:50 UTC, krashaen commented on pages/guide/elements/index.tsx
> +              onChange={this.handleInputChange}
а здесь onChange передала, но в самом компоненте не обрабатываешь его)

2020-08-06 10:55 UTC, artamonJr commented on components/Input/Input.tsx
> +import styles from './Input.module.scss';
> А зачем у стилей сначала `.module`?)

в доке по nextjs так написано делать, типо конвенция именования для поддержки css modules

2020-08-06 12:53 UTC, arlgnv requested changes

2020-08-06 12:53 UTC, artamonJr commented on components/Input/Input.module.scss
> +  width: 100%;
зачем два раза width?)

2020-08-06 12:53 UTC, artamonJr commented on components/Input/Input.module.scss
> +  height: 44px;
не используй height

2020-08-06 12:53 UTC, artamonJr commented on components/Input/Input.module.scss
> +  height: 44px;
и используй rem в качестве единиц измерения

2020-08-06 12:53 UTC, artamonJr commented on components/Input/Input.module.scss
> +  border: 1px solid rgba(31, 32, 65, 0.25);
цвета в константы нужно вынести

2020-08-06 12:53 UTC, artamonJr commented on components/Input/Input.module.scss
> +  font-family: Montserrat, Arial, sans-serif;
шрифт и цвет шрифта нужно указать глобально

2020-08-06 12:53 UTC, artamonJr commented on components/Input/Input.module.scss
> +  font-family: Montserrat, Arial, sans-serif;
соблюдать best practices никто не отменял)

2020-08-06 12:53 UTC, artamonJr commented on components/Input/Input.module.scss
> +  &::placeholder {
для placeholder у инпута есть еще стили в макете

2020-08-06 12:53 UTC, artamonJr commented on pages/guide/elements/Elements.module.scss
> +.elements{
файл лучше обозвать elements. С маленькой буквы

2020-08-06 12:53 UTC, artamonJr commented on pages/guide/elements/Elements.module.scss
> +    &-error{
вот так лучше не разделять, потому что это ухудшает ясность кода и затрудняет его чтение.
Когда я вижу структуру &__lala {}, то в ней я подозреваю найти стили относящиеся к lala элементу, а вот lala-error - это уже другой элемент, соответственно стили для него лучше держать в &__lala-error {}

2020-08-06 12:53 UTC, artamonJr commented on pages/guide/elements/index.tsx
> +import Input from '../../../components/Input/Input';
можно как-нибудь придумать, чтобы были доступны импорты из корня проекта? чтобы избавиться от кода типо `'../../../../../../../components/Input/Input'`

2020-08-06 12:53 UTC, artamonJr commented on pages/guide/elements/index.tsx
> +    this.handleInputChange = this.handleInputChange.bind(this);
мне кажется, в nextjs можно использовать class properties, чтобы избавиться от необходимости биндить обработчики. Либо, можешь воспользовать [декораторами](https://www.npmjs.com/package/core-decorators)

2020-08-06 12:53 UTC, artamonJr commented on styles/mixins/font-face.scss
> +         url(../../public/fonts/#{$font}-#{$type}.ttf) format('ttf');
шрифты должны быть только woff2 и woff

2020-08-06 12:53 UTC, artamonJr commented on pages/guide/elements/index.tsx
> +        fieldValidationErrors.email = emailValid ? '' : 'Некорректный email';
зачем перезатирать пустую строку пустой строкой?
лучше что-то типа `!emailValid && 'Некорректный email'`

2020-08-06 12:53 UTC, artamonJr commented on pages/guide/elements/index.tsx
> +        fieldValidationErrors.email = emailValid ? '' : 'Некорректный email';
и во-вторых, ты мутируешь state, а это очень плохо. State локальный в реакте не должен мутироваться

2020-08-11 02:42 UTC, krashaen commented on components/Input/Input.tsx
> +  const handleInputChange = (e) => {
по хорошему тут бы эвент затипизировать

2020-08-11 02:42 UTC, krashaen commented on components/Input/Input.tsx
> +    const inputValue = e.target.value;
тут чисто вкусовщина, но у нас в большинстве случаев юзают деструктуризацию
```
const { name, value } = e.target
```

2020-08-11 02:42 UTC, krashaen commented on pages/guide/elements/index.tsx
> +      formErrors: { email: '', name: '' },
а где интерфейс для стейта?)

2020-08-11 02:42 UTC, krashaen commented on components/Input/Input.tsx
> +const Input: React.FC = ({
где интерфейс для пропсов?)
я понимаю что FC сам подставляет типизацию, но сейчас не понятно какие из кучи пропсов инпута ты юзаешь

2020-08-11 02:42 UTC, krashaen commented on pages/guide/elements/index.tsx
> +  constructor(props) {
тоже вкусовщина, но в команде мы уже давно почти на всех проектах стейт объявляем не через конструктор а через поле класса, примерно так:
```typescript
public state: IState = { name:'', email: '',  formErrors: { email: '', name: '' }};
```

2020-08-12 04:10 UTC, Olga-Skoroded commented on components/Input/Input.tsx
> +const Input: React.FC = ({
Добавила, можно закрывать?

2020-08-12 04:12 UTC, Olga-Skoroded commented on pages/guide/elements/index.tsx
> +              onChange={this.handleInputChange}
Но в самом компоненте же он вызывается и state обновляется. Или еще что-то нужно сделать?

2020-08-13 02:42 UTC, krashaen approved these changes

2020-08-14 03:40 UTC, merged