16 create time filter
Olga-Skoroded/toxin-group-project pull request #73
Opened 2020-09-14 22:52 UTC by SigidinIlya

2020-09-15 02:42 UTC, Olga-Skoroded reviewed
Ховер у дат тоже наверное лучше круглым сделать
Если кликнуть на текущую дату, она становится квадратной 
![calendar](https://user-images.githubusercontent.com/68814270/93158950-69e37e00-f737-11ea-8b64-26e4965a84ff.gif)

2020-09-15 02:42 UTC, Olga-Skoroded commented on components/TimePicker/TimePicker.styles.tsx
> +export { Form, ExpandIcon, FormElement };
Тут тоже экспорты вертикально сделай)

2020-09-15 11:31 UTC, SigidinIlya commented on components/TimePicker/TimePicker.styles.tsx
> +export { Form, ExpandIcon, FormElement };
Готово)

2020-09-15 15:13 UTC, Fr0stmourne reviewed
Еще один коммент по функционалу - думаю, стоит как с дропдауном, сделать закрытие календаря по клику вне его)

2020-09-15 15:13 UTC, Fr0stmourne commented on components/Calendar/Calendar.tsx
> +  const has = Object.prototype.hasOwnProperty;
а зачем тут забирать метод из прототипа и вызывать потом через call? если просто чтобы писать has вместо hasOwnProperty, то это неочевидное применение и нужно лишний раз думать, почему тут так написано. Мне кажется, проще использовать обычную запись, читается тоже лучше)

2020-09-15 15:13 UTC, Fr0stmourne commented on components/Calendar/Calendar.tsx
> +  const isSelectingFirstDay = (dateFrom, dateTo, currentDay) => {
наверное, тут лучше затипизировать параметры, а то там any везде

2020-09-15 15:13 UTC, Fr0stmourne commented on components/Calendar/Calendar.tsx
> +  enteredTo?: boolean | Date;
не очень очевидно, почему тут еще и boolean возможен, и дальше там ошибки в типах из-за этого, может как-то иначе можно сделать?

2020-09-15 15:13 UTC, Fr0stmourne commented on components/Calendar/Calendar.tsx
> +  const handleApplyButtonClick = (e): void => {
события бы лучше тоже затипизировать)

2020-09-15 15:13 UTC, Fr0stmourne commented on components/Calendar/Calendar.tsx
> +      </S.CalendarControls>
эти кнопки уже в мастере есть как отдельный компонент, так что можешь заменить)

2020-09-15 15:37 UTC, Fr0stmourne commented on components/Calendar/Calendar.styles.tsx
> +            content: '←';
У таких стрелочек дизайн отличается, поэтому лучше все же иконку из макета взять)

2020-09-16 08:50 UTC, SigidinIlya commented on components/Calendar/Calendar.tsx
> +  const has = Object.prototype.hasOwnProperty;
Airbnb пункт 3.7

2020-09-16 08:52 UTC, SigidinIlya commented on components/Calendar/Calendar.styles.tsx
> +            content: '←';
Здесь плагин подключается, поэтому у меня нет доступа к этим кнопкам, поэтому я решил использовать знак стрелки в псевдоселекторе )

2020-09-17 06:34 UTC, Fr0stmourne commented on components/Calendar/Calendar.styles.tsx
> +            content: '←';
здесь можно просто в css подключить material-icons, там эта иконка есть

2020-09-17 15:45 UTC, Fr0stmourne commented on components/TimePicker/TimePicker.tsx
> +          name="date from"
если будет несколько таймпикеров на странице, то имена будут одинаковые, что не очень хорошо. как я понял, мы все-таки юзаем final-form, думаю стоит компонент обернуть в Field оттуда

2020-09-17 15:45 UTC, Fr0stmourne commented on components/TimePicker/TimePicker.tsx
> +    <S.Form>
здесь не стоит в форму оборачивать, это же один инпут, который будет где-то в форме использоваться, получится форма в форме

2020-09-17 22:12 UTC, SigidinIlya commented on components/TimePicker/TimePicker.tsx
> +          name="date from"
Но ты же ниже написал что нужно форму убрать, а без формы Field не работает)
Поэтому я решил сделать немного иначе, и название этих инпутов берём из пропсов.

2020-09-17 22:12 UTC, SigidinIlya commented on components/TimePicker/TimePicker.tsx
> +    <S.Form>
готово

2020-09-18 02:46 UTC, Olga-Skoroded approved these changes

2020-09-22 08:45 UTC, Fr0stmourne commented on components/TimePicker/TimePicker.tsx
> +          name="date from"
Все-таки обернули

2020-09-22 08:53 UTC, AkhmadBabaev commented
![mst](https://user-images.githubusercontent.com/51095975/93862041-26a28580-fcca-11ea-8dd1-ced30a4c371b.gif)

2020-09-22 08:57 UTC, AkhmadBabaev commented
![image](https://user-images.githubusercontent.com/51095975/93862311-81d47800-fcca-11ea-9962-40dd22ddccc9.png)

2020-09-22 09:09 UTC, Fr0stmourne commented on components/TimePicker/TimePicker.styles.tsx
> +      width: ${type === 'single' ? '100%' : '47%'};
какая-то тут странная величина 47%, если нужно задать фиксированный размер, лучше в абсолютных единицах измерения

2020-09-22 09:11 UTC, SigidinIlya commented on components/TimePicker/TimePicker.styles.tsx
> +      width: ${type === 'single' ? '100%' : '47%'};
это ширина в случае 2 input'ов, т.к у родителя space-between, таким образом между инпутов образуется необходимое по макету расстояние

2020-09-22 09:12 UTC, Fr0stmourne commented on components/TimePicker/TimePicker.styles.tsx
> +      width: ${type === 'single' ? '100%' : '47%'};
по идее, достаточно просто задать margin-right у одного из них)

2020-09-22 09:37 UTC, AkhmadBabaev commented on components/TimePicker/TimePicker.tsx
> +                placeholder="date to"
Может добавить атрибут **readOnly** ?

2020-09-22 09:58 UTC, SigidinIlya commented on components/TimePicker/TimePicker.styles.tsx
> +      width: ${type === 'single' ? '100%' : '47%'};
Поправил

2020-09-22 10:06 UTC, Fr0stmourne approved these changes

2020-09-22 11:42 UTC, AkhmadBabaev approved these changes

2020-09-22 12:41 UTC, krashaen requested changes

2020-09-22 12:41 UTC, krashaen commented on pages/guide/elements/index.tsx
> +  handleFormSubmit = () => { };
что за обработчик так такой классный?)

2020-09-22 12:53 UTC, krashaen approved these changes

2020-09-22 13:37 UTC, merged