component is done
Olga-Skoroded/toxin-group-project pull request #92
Opened 2020-09-16 20:09 UTC by SigidinIlya

2020-09-17 14:37 UTC, Fr0stmourne commented on components/Benefits/Benefits.style.ts
> +        content: '${'' + icon}';
а чего не просто `content: '${icon}';` ?

2020-09-17 14:37 UTC, Fr0stmourne commented on components/Benefits/Benefits.tsx
> +        <S.BenefitItem key={Number(index).toString()}>
думаю, лучше в key передать item.title тут )

2020-09-17 15:18 UTC, AkhmadBabaev commented
Кажется **package-lock.json** случайно оказался в индексе.

2020-09-17 16:02 UTC, AkhmadBabaev commented
По pixel perfect надо поправить )

2020-09-17 16:03 UTC, AkhmadBabaev commented on components/Benefits/Benefits.style.ts
> +        content: '${'' + icon}';
В свойстве display: block у before на текущий момент нет необходимости.

2020-09-17 16:03 UTC, AkhmadBabaev commented on pages/guide/elements/index.tsx
>  import CheckboxesList from 'components/CheckboxesList/CheckboxesList';
Остальные компоненты импортированы без @.

2020-09-17 16:03 UTC, AkhmadBabaev commented on components/Benefits/Benefits.style.ts
> +        content: '${'' + icon}';
```ts
width: 3.2rem;
height: 3.2rem;
```

Надо пересмотреть эти строки, так как они вызывают такой эффект в firefox 
![image](https://user-images.githubusercontent.com/51095975/93495804-33645980-f917-11ea-8f14-5c972e5a15f3.png)

2020-09-17 16:03 UTC, AkhmadBabaev commented on components/Benefits/Benefits.style.ts
> +  margin: 0.2rem 0 0.5rem 0;
**margin** сверху не нужен, заголовок и описание должны центрироваться относительно высоты иконки.

2020-09-17 22:19 UTC, SigidinIlya commented
> По pixel perfect надо поправить )

![image](https://user-images.githubusercontent.com/70949093/93534024-f024dd80-f94c-11ea-91fc-3f9def62d71d.png)

2020-09-17 22:26 UTC, SigidinIlya commented on components/Benefits/Benefits.style.ts
> +  margin: 0.2rem 0 0.5rem 0;
Нет, в макете есть небольшой отступ 
![image](https://user-images.githubusercontent.com/70949093/93534369-9ffa4b00-f94d-11ea-830d-91a7c92a7c6a.png)

Поэтому, я установил line-height, как минимум это полностью заменило текущий margin )

2020-09-18 02:49 UTC, Olga-Skoroded approved these changes

2020-09-18 07:42 UTC, Fr0stmourne commented on components/Benefits/Benefits.style.ts
> +}
я бы этот тип прокинул еще в основной компонент и объединил с title и description, чтобы icon не дублировать

2020-09-18 09:41 UTC, AkhmadBabaev commented on components/Benefits/Benefits.style.ts
> +  margin: 0.2rem 0 0.5rem 0;
Отступ есть но он решается центрированием текста по вертикальной оси относительно относительно иконки.

2020-09-18 10:01 UTC, AkhmadBabaev requested changes

2020-09-18 10:01 UTC, AkhmadBabaev commented on components/Benefits/Benefits.style.ts
> +
Не знаю как дальше пойдёт, но если после правок всё ещё не будет стилей в тэге, можно будет это удалить.

2020-09-18 10:01 UTC, AkhmadBabaev commented on components/Benefits/Benefits.tsx
> +
Тут можно использовать деструктуризацию сразу в пропсах и сразу возвращать компонент.

2020-09-18 10:01 UTC, AkhmadBabaev commented on components/Benefits/Benefits.tsx
> +          <S.TextWrapper>
Скорее всего ты забыл удалить className.

2020-09-18 10:01 UTC, AkhmadBabaev commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz",
Новый пакет ты не качал, а изменения в package-lock.json всё ещё есть.

2020-09-20 18:57 UTC, SigidinIlya commented on components/Benefits/Benefits.style.ts
> +}
Поправил

2020-09-20 18:57 UTC, SigidinIlya commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz",
Поправил

2020-09-21 03:06 UTC, krashaen approved these changes

2020-09-21 08:26 UTC, Fr0stmourne approved these changes

2020-09-21 08:31 UTC, AkhmadBabaev approved these changes

2020-09-21 08:42 UTC, merged